/*
 * Generated by ISE 15.08.9.7862 GPL Edition - linux-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F286_6846();
extern void F288_6999();
extern void F293_7068();
extern void F294_7207();
extern void F311_4153();
extern void F310_6727();
extern void F167_2173();
extern EIF_REFERENCE F167_2160();
extern EIF_BOOLEAN F167_2172();
extern EIF_BOOLEAN F167_2177();
extern void F167_2182();
extern void F167_2183();
extern void F167_2184();
extern void F100_1703();
extern EIF_TYPED_VALUE F100_1704();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F286_6846;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F293_7068;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F311_4153;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F288_6999;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F294_7207;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F310_6727;
					#ifdef RTS_SCP_CAPABLE
						egc_is_scoop_capable = 1;
					#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F167_2173;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F167_2172;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F167_2160;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F167_2177;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F167_2182;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F167_2183;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F167_2184;

	egc_str_dtype = 287;

	egc_str32_dtype = 293;
	egc_arr_dtype = 310;
	egc_tup_dtype = 241;
	egc_disp_rout_id = 3129;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0272;
	egc_sp_wchar = 0x0362;
	egc_sp_bool = 0x023A;
	egc_sp_uint8 = 0x02FA;
	egc_sp_uint16 = 0x02DB;
	egc_sp_uint32 = 0x01B2;
	egc_sp_uint64 = 0x01D8;
	egc_sp_int8 = 0x0254;
	egc_sp_int16 = 0x031E;
	egc_sp_int32 = 0x0159;
	egc_sp_int64 = 0x033F;
	egc_sp_real32 = 0x0297;
	egc_sp_real64 = 0x0186;
	egc_sp_pointer = 0x01F6;
	egc_sp_ref = 0x0145;

	egc_uint8_dtype = 261;
	egc_uint16_dtype = 270;
	egc_uint32_dtype = 267;
	egc_uint64_dtype = 279;
	egc_int8_dtype = 243;
	egc_int16_dtype = 276;
	egc_int32_dtype = 273;
	egc_int64_dtype = 252;
	egc_bool_dtype = 255;
	egc_real32_dtype = 264;
	egc_char_dtype = 249;
	egc_wchar_dtype = 246;
	egc_real64_dtype = 258;
	egc_point_dtype = 282;

	egc_exception_dtype = 116;
	egc_except_emnger_dtype = 166;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "roboscoop_lib";
	egc_system_location = "/home/frank/catkin_group_workspace/src/lanke_marius_xiote/roboscoop/roboscoop_lib/EIFGENs/roboscoop/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1450377148;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 929;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "ANY";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = -1;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 99;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F100_1703;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F100_1704;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 0; /* ANY */
	}
}

#ifdef __cplusplus
}
#endif
